name: Reusable CI

on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build component
        run: echo "Building ${{ inputs.component }}"
      - name: Test component
        run: echo "Testing ${{ inputs.component }}"
